### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by hikkie3110** [hippich/twitter-auto-oauth#1]
Hi, I'm HikaruSAITOH from Japan.
This script is very beneficial, so I wanna use it to make many twitter bots .

Bt the way, I have  one question.
How to use this script?

I did
・install npm
・install moncha

$ cd twitter-auto-auth
$ TWITTER_USERNAME=username TWITTER_PASSWORD=password CONSUMER_KEY=kkkkkkkkkkkkkkkkkkkkkk CONSUMER_SECRET=ssssssssssssssssssssssssssssssssssssssssss npm test

But, result is

> twitter-auto-oauth@0.0.2 test /Applications/twitter-auto-oauth-master
> DEBUG=\* ./node_modules/.bin/mocha tests/

sh: ./node_modules/.bin/mocha: No such file or directory
npm ERR! weird error 127

why?

I want a toutrial how to use.
Could you tell me how to use this script?

**Comment by hippich** [comment]
In your particular case you do not have mocha installed properly. to do that inside project folder you should run "npm install" - and it will install all dependencies properly, including mocha.

but even with that - i just checked - something changed on twitter site, so module no longer works as is and require (probably minor) modifications. I will create separate issue for that.

**Comment by hikkie3110** [comment]
I  appreciate for your reply  and undersand.

thx for your  corporation!
